name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Call send notification api
      run: curl -X POST -H 'Content-Type: application/json' -d "{\"token\": \"$TELEGRAM_TOKEN\"}" https://hydrome-bot.now.sh/api/send-notifications
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}